name: "✨ Feature"
description: "새 기능 추가"
labels: ["feature"]
body:
  - type: dropdown
    id: domain
    attributes:
      label: 도메인
      options:
        - auth
        - post
        - chat
        - notification
        - infra
    validations:
      required: true

  - type: dropdown
    id: layer
    attributes:
      label: 레이어
      options:
        - backend
        - frontend
        - both
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 설명
      placeholder: 어떤 기능인지 간단히 설명
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 작업 내용
      value: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: 참고 사항
      placeholder: 관련 링크, 스크린샷 등